<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE object
[
   <!ELEMENT object (#PCDATA|object)*>
   <!ATTLIST object name      CDATA #REQUIRED>
   <!ATTLIST object class     CDATA #REQUIRED>
   <!ATTLIST object primitive CDATA "no">
   <!ATTLIST object array     CDATA "no">   <!-- the dimensions of the array; no=0, yes=1 -->
   <!ATTLIST object null      CDATA "no">
   <!ATTLIST object version   CDATA "3.7.13-SNAPSHOT">
]
>

<object class="weka.experiment.RemoteExperiment" name="__root__" version="3.7.13-SNAPSHOT">
   <object array="yes" class="weka.classifiers.Classifier" name="propertyArray">
      <object class="weka.classifiers.meta.CostSensitiveClassifier" name="0">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-cost-matrix</object>
            <object class="java.lang.String" name="1">[0.0 1.0 4.0 9.0 16.0 25.0 36.0 49.0 64.0 81.0; 1.0 0.0 1.0 4.0 9.0 16.0 25.0 36.0 49.0 64.0; 4.0 1.0 0.0 1.0 4.0 9.0 16.0 25.0 36.0 49.0; 9.0 4.0 1.0 0.0 1.0 4.0 9.0 16.0 25.0 36.0; 16.0 9.0 4.0 1.0 0.0 1.0 4.0 9.0 16.0 25.0; 25.0 16.0 9.0 4.0 1.0 0.0 1.0 4.0 9.0 16.0; 36.0 25.0 16.0 9.0 4.0 1.0 0.0 1.0 4.0 9.0; 49.0 36.0 25.0 16.0 9.0 4.0 1.0 0.0 1.0 4.0; 64.0 49.0 36.0 25.0 16.0 9.0 4.0 1.0 0.0 1.0; 81.0 64.0 49.0 36.0 25.0 16.0 9.0 4.0 1.0 0.0]</object>
            <object class="java.lang.String" name="2">-M</object>
            <object class="java.lang.String" name="3">-S</object>
            <object class="java.lang.String" name="4">1</object>
            <object class="java.lang.String" name="5">-W</object>
            <object class="java.lang.String" name="6">weka.classifiers.pyscript.PyScriptClassifier</object>
            <object class="java.lang.String" name="7">--</object>
            <object class="java.lang.String" name="8">-args</object>
            <object class="java.lang.String" name="9">a=1;b=0;logistic=True;alpha=0.1;epochs=5000;schedule=500</object>
            <object class="java.lang.String" name="10">-batch</object>
            <object class="java.lang.String" name="11">10000</object>
            <object class="java.lang.String" name="12">-cmd</object>
            <object class="java.lang.String" name="13">python</object>
            <object class="java.lang.String" name="14">-script</object>
            <object class="java.lang.String" name="15">/home/cjb60/github/weka-pyscript-examples/test-kappa/train.py</object>
            <object class="java.lang.String" name="16">-binarize</object>
            <object class="java.lang.String" name="17">-impute</object>
            <object class="java.lang.String" name="18">-standardize</object>
         </object>
      </object>
      <object class="weka.classifiers.pyscript.PyScriptClassifier" name="1">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-args</object>
            <object class="java.lang.String" name="1">a=1;b=0;expectation=True;logistic=True;alpha=0.1;schedule=500;epochs=5000</object>
            <object class="java.lang.String" name="2">-batch</object>
            <object class="java.lang.String" name="3">10000</object>
            <object class="java.lang.String" name="4">-cmd</object>
            <object class="java.lang.String" name="5">python</object>
            <object class="java.lang.String" name="6">-script</object>
            <object class="java.lang.String" name="7">/home/cjb60/github/weka-pyscript-examples/test-kappa/train.py</object>
            <object class="java.lang.String" name="8">-binarize</object>
            <object class="java.lang.String" name="9">-impute</object>
            <object class="java.lang.String" name="10">-standardize</object>
         </object>
      </object>
      <object class="weka.classifiers.pyscript.PyScriptClassifier" name="2">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-args</object>
            <object class="java.lang.String" name="1">a=1;b=0.5;expectation=True;logistic=True;alpha=0.1;schedule=500;epochs=5000</object>
            <object class="java.lang.String" name="2">-batch</object>
            <object class="java.lang.String" name="3">10000</object>
            <object class="java.lang.String" name="4">-cmd</object>
            <object class="java.lang.String" name="5">python</object>
            <object class="java.lang.String" name="6">-script</object>
            <object class="java.lang.String" name="7">/home/cjb60/github/weka-pyscript-examples/test-kappa/train.py</object>
            <object class="java.lang.String" name="8">-binarize</object>
            <object class="java.lang.String" name="9">-impute</object>
            <object class="java.lang.String" name="10">-standardize</object>
         </object>
      </object>
      <object class="weka.classifiers.pyscript.PyScriptClassifier" name="3">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-args</object>
            <object class="java.lang.String" name="1">a=1;b=1;expectation=True;logistic=True;alpha=0.1;schedule=500;epochs=5000</object>
            <object class="java.lang.String" name="2">-batch</object>
            <object class="java.lang.String" name="3">10000</object>
            <object class="java.lang.String" name="4">-cmd</object>
            <object class="java.lang.String" name="5">python</object>
            <object class="java.lang.String" name="6">-script</object>
            <object class="java.lang.String" name="7">/home/cjb60/github/weka-pyscript-examples/test-kappa/train.py</object>
            <object class="java.lang.String" name="8">-binarize</object>
            <object class="java.lang.String" name="9">-impute</object>
            <object class="java.lang.String" name="10">-standardize</object>
         </object>
      </object>
      <object class="weka.classifiers.pyscript.PyScriptClassifier" name="4">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-args</object>
            <object class="java.lang.String" name="1">a=1;b=1.5;expectation=True;logistic=True;alpha=0.1;schedule=500;epochs=5000</object>
            <object class="java.lang.String" name="2">-batch</object>
            <object class="java.lang.String" name="3">10000</object>
            <object class="java.lang.String" name="4">-cmd</object>
            <object class="java.lang.String" name="5">python</object>
            <object class="java.lang.String" name="6">-script</object>
            <object class="java.lang.String" name="7">/home/cjb60/github/weka-pyscript-examples/test-kappa/train.py</object>
            <object class="java.lang.String" name="8">-binarize</object>
            <object class="java.lang.String" name="9">-impute</object>
            <object class="java.lang.String" name="10">-standardize</object>
         </object>
      </object>
      <object class="weka.classifiers.pyscript.PyScriptClassifier" name="5">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-args</object>
            <object class="java.lang.String" name="1">a=1;b=2.0;expectation=True;logistic=True;alpha=0.1;schedule=500;epochs=5000</object>
            <object class="java.lang.String" name="2">-batch</object>
            <object class="java.lang.String" name="3">10000</object>
            <object class="java.lang.String" name="4">-cmd</object>
            <object class="java.lang.String" name="5">python</object>
            <object class="java.lang.String" name="6">-script</object>
            <object class="java.lang.String" name="7">/home/cjb60/github/weka-pyscript-examples/test-kappa/train.py</object>
            <object class="java.lang.String" name="8">-binarize</object>
            <object class="java.lang.String" name="9">-impute</object>
            <object class="java.lang.String" name="10">-standardize</object>
         </object>
      </object>
      <object class="weka.classifiers.pyscript.PyScriptClassifier" name="6">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-args</object>
            <object class="java.lang.String" name="1">a=0;b=1;expectation=True;logistic=True;alpha=0.1;schedule=500;epochs=5000</object>
            <object class="java.lang.String" name="2">-batch</object>
            <object class="java.lang.String" name="3">10000</object>
            <object class="java.lang.String" name="4">-cmd</object>
            <object class="java.lang.String" name="5">python</object>
            <object class="java.lang.String" name="6">-script</object>
            <object class="java.lang.String" name="7">/home/cjb60/github/weka-pyscript-examples/test-kappa/train.py</object>
            <object class="java.lang.String" name="8">-binarize</object>
            <object class="java.lang.String" name="9">-impute</object>
            <object class="java.lang.String" name="10">-standardize</object>
         </object>
      </object>
      <object class="weka.classifiers.pyscript.PyScriptClassifier" name="7">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-args</object>
            <object class="java.lang.String" name="1">regression=True;alpha=0.1;schedule=500;epochs=5000</object>
            <object class="java.lang.String" name="2">-batch</object>
            <object class="java.lang.String" name="3">10000</object>
            <object class="java.lang.String" name="4">-cmd</object>
            <object class="java.lang.String" name="5">python</object>
            <object class="java.lang.String" name="6">-script</object>
            <object class="java.lang.String" name="7">/home/cjb60/github/weka-pyscript-examples/test-kappa/train.py</object>
            <object class="java.lang.String" name="8">-binarize</object>
            <object class="java.lang.String" name="9">-impute</object>
            <object class="java.lang.String" name="10">-standardize</object>
         </object>
      </object>
   </object>
   <object class="boolean" name="splitByDataSet" primitive="yes">false</object>
   <object class="javax.swing.DefaultListModel" name="datasets">
      <object class="java.io.File" name="0">/home/cjb60/github/weka-pyscript-examples/test-kappa/data/2dplanes.arff</object>
      <object class="java.io.File" name="1">/home/cjb60/github/weka-pyscript-examples/test-kappa/data/abalone.arff</object>
      <object class="java.io.File" name="2">/home/cjb60/github/weka-pyscript-examples/test-kappa/data/ailerons.arff</object>
      <object class="java.io.File" name="3">/home/cjb60/github/weka-pyscript-examples/test-kappa/data/autoMpg.arff</object>
      <object class="java.io.File" name="4">/home/cjb60/github/weka-pyscript-examples/test-kappa/data/auto_price.arff</object>
      <object class="java.io.File" name="5">/home/cjb60/github/weka-pyscript-examples/test-kappa/data/bank32nh.arff</object>
      <object class="java.io.File" name="6">/home/cjb60/github/weka-pyscript-examples/test-kappa/data/bank8FM.arff</object>
      <object class="java.io.File" name="7">/home/cjb60/github/weka-pyscript-examples/test-kappa/data/cal_housing.arff</object>
      <object class="java.io.File" name="8">/home/cjb60/github/weka-pyscript-examples/test-kappa/data/cpu_act.arff</object>
      <object class="java.io.File" name="9">/home/cjb60/github/weka-pyscript-examples/test-kappa/data/cpu_small.arff</object>
      <object class="java.io.File" name="10">/home/cjb60/github/weka-pyscript-examples/test-kappa/data/delta_ailerons.arff</object>
      <object class="java.io.File" name="11">/home/cjb60/github/weka-pyscript-examples/test-kappa/data/delta_elevators.arff</object>
      <object class="java.io.File" name="12">/home/cjb60/github/weka-pyscript-examples/test-kappa/data/diabetes_numeric.arff</object>
      <object class="java.io.File" name="13">/home/cjb60/github/weka-pyscript-examples/test-kappa/data/elevators.arff</object>
      <object class="java.io.File" name="14">/home/cjb60/github/weka-pyscript-examples/test-kappa/data/fried.arff</object>
      <object class="java.io.File" name="15">/home/cjb60/github/weka-pyscript-examples/test-kappa/data/house_16H.arff</object>
      <object class="java.io.File" name="16">/home/cjb60/github/weka-pyscript-examples/test-kappa/data/house_8L.arff</object>
      <object class="java.io.File" name="17">/home/cjb60/github/weka-pyscript-examples/test-kappa/data/housing.arff</object>
      <object class="java.io.File" name="18">/home/cjb60/github/weka-pyscript-examples/test-kappa/data/kin8nm.arff</object>
      <object class="java.io.File" name="19">/home/cjb60/github/weka-pyscript-examples/test-kappa/data/machine_cpu.arff</object>
      <object class="java.io.File" name="20">/home/cjb60/github/weka-pyscript-examples/test-kappa/data/mv.arff</object>
      <object class="java.io.File" name="21">/home/cjb60/github/weka-pyscript-examples/test-kappa/data/puma32H.arff</object>
      <object class="java.io.File" name="22">/home/cjb60/github/weka-pyscript-examples/test-kappa/data/puma8NH.arff</object>
      <object class="java.io.File" name="23">/home/cjb60/github/weka-pyscript-examples/test-kappa/data/pyrim.arff</object>
      <object class="java.io.File" name="24">/home/cjb60/github/weka-pyscript-examples/test-kappa/data/servo.arff</object>
      <object class="java.io.File" name="25">/home/cjb60/github/weka-pyscript-examples/test-kappa/data/stock.arff</object>
      <object class="java.io.File" name="26">/home/cjb60/github/weka-pyscript-examples/test-kappa/data/triazines.arff</object>
      <object class="java.io.File" name="27">/home/cjb60/github/weka-pyscript-examples/test-kappa/data/wisconsin.arff</object>
   </object>
   <object class="javax.swing.DefaultListModel" name="remoteHosts">
      <object class="java.lang.String" name="0">ml64-30.cms.waikato.ac.nz:9005</object>
      <object class="java.lang.String" name="1">ml64-30.cms.waikato.ac.nz:9006</object>
      <object class="java.lang.String" name="2">ml64-30.cms.waikato.ac.nz:9007</object>
      <object class="java.lang.String" name="3">ml64-31.cms.waikato.ac.nz:9005</object>
      <object class="java.lang.String" name="4">ml64-31.cms.waikato.ac.nz:9006</object>
      <object class="java.lang.String" name="5">ml64-31.cms.waikato.ac.nz:9007</object>
      <object class="java.lang.String" name="6">ml64-33.cms.waikato.ac.nz:9005</object>
      <object class="java.lang.String" name="7">ml64-33.cms.waikato.ac.nz:9006</object>
      <object class="java.lang.String" name="8">ml64-33.cms.waikato.ac.nz:9007</object>
      <object class="java.lang.String" name="9">ml64-34.cms.waikato.ac.nz:9006</object>
      <object class="java.lang.String" name="10">ml64-34.cms.waikato.ac.nz:9005</object>
      <object class="java.lang.String" name="11">ml64-34.cms.waikato.ac.nz:9007</object>
   </object>
   <object class="int" name="runUpper" primitive="yes">4</object>
   <object class="weka.experiment.CrossValidationResultProducer" name="resultProducer">
      <object array="yes" class="java.lang.String" name="options">
         <object class="java.lang.String" name="0">-X</object>
         <object class="java.lang.String" name="1">10</object>
         <object class="java.lang.String" name="2">-O</object>
         <object class="java.lang.String" name="3">splitEvalutorOut.zip</object>
         <object class="java.lang.String" name="4">-W</object>
         <object class="java.lang.String" name="5">weka.experiment.ClassifierSplitEvaluator</object>
         <object class="java.lang.String" name="6">--</object>
         <object class="java.lang.String" name="7">-W</object>
         <object class="java.lang.String" name="8">weka.classifiers.rules.ZeroR</object>
         <object class="java.lang.String" name="9">-I</object>
         <object class="java.lang.String" name="10">0</object>
         <object class="java.lang.String" name="11">-C</object>
         <object class="java.lang.String" name="12">1</object>
         <object class="java.lang.String" name="13">--</object>
      </object>
   </object>
   <object class="boolean" name="usePropertyIterator" primitive="yes">true</object>
   <object array="yes" class="weka.experiment.PropertyNode" name="propertyPath">
      <object array="no" class="weka.experiment.PropertyNode" name="0" primitive="no">
         <object class="weka.experiment.ClassifierSplitEvaluator" name="value">
            <object array="yes" class="java.lang.String" name="options">
               <object class="java.lang.String" name="0">-W</object>
               <object class="java.lang.String" name="1">weka.classifiers.rules.ZeroR</object>
               <object class="java.lang.String" name="2">-I</object>
               <object class="java.lang.String" name="3">0</object>
               <object class="java.lang.String" name="4">-C</object>
               <object class="java.lang.String" name="5">1</object>
               <object class="java.lang.String" name="6">--</object>
            </object>
         </object>
         <object class="java.lang.String" name="parentClass">weka.experiment.CrossValidationResultProducer</object>
         <object class="java.lang.String" name="property">splitEvaluator</object>
      </object>
      <object array="no" class="weka.experiment.PropertyNode" name="1" primitive="no">
         <object class="weka.classifiers.rules.ZeroR" name="value">
            <object class="boolean" name="debug" primitive="yes">false</object>
            <object array="yes" class="java.lang.String" name="options"/>
         </object>
         <object class="java.lang.String" name="parentClass">weka.experiment.ClassifierSplitEvaluator</object>
         <object class="java.lang.String" name="property">classifier</object>
      </object>
   </object>
   <object class="java.lang.String" name="notes"/>
   <object class="weka.experiment.DatabaseResultListener" name="resultListener">
      <object class="java.lang.String" name="keywordsMaskChar">_</object>
      <object class="java.lang.String" name="cacheKeyName"/>
      <object class="boolean" name="debug" primitive="yes">false</object>
      <object class="java.lang.String" name="password"/>
      <object class="java.lang.String" name="keywords">AND,ASC,BY,DESC,FROM,GROUP,INSERT,ORDER,SELECT,UPDATE,WHERE</object>
      <object class="java.lang.String" name="databaseURL">jdbc:hsqldb:hsql://ml64-33.cms.waikato.ac.nz/</object>
      <object class="java.lang.String" name="username"/>
   </object>
   <object class="weka.experiment.Experiment" name="baseExperiment">
      <object array="yes" class="weka.classifiers.Classifier" name="propertyArray">
         <object class="weka.classifiers.meta.CostSensitiveClassifier" name="0">
            <object class="boolean" name="debug" primitive="yes">false</object>
            <object array="yes" class="java.lang.String" name="options">
               <object class="java.lang.String" name="0">-cost-matrix</object>
               <object class="java.lang.String" name="1">[0.0 1.0 4.0 9.0 16.0 25.0 36.0 49.0 64.0 81.0; 1.0 0.0 1.0 4.0 9.0 16.0 25.0 36.0 49.0 64.0; 4.0 1.0 0.0 1.0 4.0 9.0 16.0 25.0 36.0 49.0; 9.0 4.0 1.0 0.0 1.0 4.0 9.0 16.0 25.0 36.0; 16.0 9.0 4.0 1.0 0.0 1.0 4.0 9.0 16.0 25.0; 25.0 16.0 9.0 4.0 1.0 0.0 1.0 4.0 9.0 16.0; 36.0 25.0 16.0 9.0 4.0 1.0 0.0 1.0 4.0 9.0; 49.0 36.0 25.0 16.0 9.0 4.0 1.0 0.0 1.0 4.0; 64.0 49.0 36.0 25.0 16.0 9.0 4.0 1.0 0.0 1.0; 81.0 64.0 49.0 36.0 25.0 16.0 9.0 4.0 1.0 0.0]</object>
               <object class="java.lang.String" name="2">-M</object>
               <object class="java.lang.String" name="3">-S</object>
               <object class="java.lang.String" name="4">1</object>
               <object class="java.lang.String" name="5">-W</object>
               <object class="java.lang.String" name="6">weka.classifiers.pyscript.PyScriptClassifier</object>
               <object class="java.lang.String" name="7">--</object>
               <object class="java.lang.String" name="8">-args</object>
               <object class="java.lang.String" name="9">a=1;b=0;logistic=True;alpha=0.1;epochs=5000;schedule=500</object>
               <object class="java.lang.String" name="10">-batch</object>
               <object class="java.lang.String" name="11">10000</object>
               <object class="java.lang.String" name="12">-cmd</object>
               <object class="java.lang.String" name="13">python</object>
               <object class="java.lang.String" name="14">-script</object>
               <object class="java.lang.String" name="15">/home/cjb60/github/weka-pyscript-examples/test-kappa/train.py</object>
               <object class="java.lang.String" name="16">-binarize</object>
               <object class="java.lang.String" name="17">-impute</object>
               <object class="java.lang.String" name="18">-standardize</object>
            </object>
         </object>
         <object class="weka.classifiers.pyscript.PyScriptClassifier" name="1">
            <object class="boolean" name="debug" primitive="yes">false</object>
            <object array="yes" class="java.lang.String" name="options">
               <object class="java.lang.String" name="0">-args</object>
               <object class="java.lang.String" name="1">a=1;b=0;expectation=True;logistic=True;alpha=0.1;schedule=500;epochs=5000</object>
               <object class="java.lang.String" name="2">-batch</object>
               <object class="java.lang.String" name="3">10000</object>
               <object class="java.lang.String" name="4">-cmd</object>
               <object class="java.lang.String" name="5">python</object>
               <object class="java.lang.String" name="6">-script</object>
               <object class="java.lang.String" name="7">/home/cjb60/github/weka-pyscript-examples/test-kappa/train.py</object>
               <object class="java.lang.String" name="8">-binarize</object>
               <object class="java.lang.String" name="9">-impute</object>
               <object class="java.lang.String" name="10">-standardize</object>
            </object>
         </object>
         <object class="weka.classifiers.pyscript.PyScriptClassifier" name="2">
            <object class="boolean" name="debug" primitive="yes">false</object>
            <object array="yes" class="java.lang.String" name="options">
               <object class="java.lang.String" name="0">-args</object>
               <object class="java.lang.String" name="1">a=1;b=0.5;expectation=True;logistic=True;alpha=0.1;schedule=500;epochs=5000</object>
               <object class="java.lang.String" name="2">-batch</object>
               <object class="java.lang.String" name="3">10000</object>
               <object class="java.lang.String" name="4">-cmd</object>
               <object class="java.lang.String" name="5">python</object>
               <object class="java.lang.String" name="6">-script</object>
               <object class="java.lang.String" name="7">/home/cjb60/github/weka-pyscript-examples/test-kappa/train.py</object>
               <object class="java.lang.String" name="8">-binarize</object>
               <object class="java.lang.String" name="9">-impute</object>
               <object class="java.lang.String" name="10">-standardize</object>
            </object>
         </object>
         <object class="weka.classifiers.pyscript.PyScriptClassifier" name="3">
            <object class="boolean" name="debug" primitive="yes">false</object>
            <object array="yes" class="java.lang.String" name="options">
               <object class="java.lang.String" name="0">-args</object>
               <object class="java.lang.String" name="1">a=1;b=1;expectation=True;logistic=True;alpha=0.1;schedule=500;epochs=5000</object>
               <object class="java.lang.String" name="2">-batch</object>
               <object class="java.lang.String" name="3">10000</object>
               <object class="java.lang.String" name="4">-cmd</object>
               <object class="java.lang.String" name="5">python</object>
               <object class="java.lang.String" name="6">-script</object>
               <object class="java.lang.String" name="7">/home/cjb60/github/weka-pyscript-examples/test-kappa/train.py</object>
               <object class="java.lang.String" name="8">-binarize</object>
               <object class="java.lang.String" name="9">-impute</object>
               <object class="java.lang.String" name="10">-standardize</object>
            </object>
         </object>
         <object class="weka.classifiers.pyscript.PyScriptClassifier" name="4">
            <object class="boolean" name="debug" primitive="yes">false</object>
            <object array="yes" class="java.lang.String" name="options">
               <object class="java.lang.String" name="0">-args</object>
               <object class="java.lang.String" name="1">a=1;b=1.5;expectation=True;logistic=True;alpha=0.1;schedule=500;epochs=5000</object>
               <object class="java.lang.String" name="2">-batch</object>
               <object class="java.lang.String" name="3">10000</object>
               <object class="java.lang.String" name="4">-cmd</object>
               <object class="java.lang.String" name="5">python</object>
               <object class="java.lang.String" name="6">-script</object>
               <object class="java.lang.String" name="7">/home/cjb60/github/weka-pyscript-examples/test-kappa/train.py</object>
               <object class="java.lang.String" name="8">-binarize</object>
               <object class="java.lang.String" name="9">-impute</object>
               <object class="java.lang.String" name="10">-standardize</object>
            </object>
         </object>
         <object class="weka.classifiers.pyscript.PyScriptClassifier" name="5">
            <object class="boolean" name="debug" primitive="yes">false</object>
            <object array="yes" class="java.lang.String" name="options">
               <object class="java.lang.String" name="0">-args</object>
               <object class="java.lang.String" name="1">a=1;b=2.0;expectation=True;logistic=True;alpha=0.1;schedule=500;epochs=5000</object>
               <object class="java.lang.String" name="2">-batch</object>
               <object class="java.lang.String" name="3">10000</object>
               <object class="java.lang.String" name="4">-cmd</object>
               <object class="java.lang.String" name="5">python</object>
               <object class="java.lang.String" name="6">-script</object>
               <object class="java.lang.String" name="7">/home/cjb60/github/weka-pyscript-examples/test-kappa/train.py</object>
               <object class="java.lang.String" name="8">-binarize</object>
               <object class="java.lang.String" name="9">-impute</object>
               <object class="java.lang.String" name="10">-standardize</object>
            </object>
         </object>
         <object class="weka.classifiers.pyscript.PyScriptClassifier" name="6">
            <object class="boolean" name="debug" primitive="yes">false</object>
            <object array="yes" class="java.lang.String" name="options">
               <object class="java.lang.String" name="0">-args</object>
               <object class="java.lang.String" name="1">a=0;b=1;expectation=True;logistic=True;alpha=0.1;schedule=500;epochs=5000</object>
               <object class="java.lang.String" name="2">-batch</object>
               <object class="java.lang.String" name="3">10000</object>
               <object class="java.lang.String" name="4">-cmd</object>
               <object class="java.lang.String" name="5">python</object>
               <object class="java.lang.String" name="6">-script</object>
               <object class="java.lang.String" name="7">/home/cjb60/github/weka-pyscript-examples/test-kappa/train.py</object>
               <object class="java.lang.String" name="8">-binarize</object>
               <object class="java.lang.String" name="9">-impute</object>
               <object class="java.lang.String" name="10">-standardize</object>
            </object>
         </object>
         <object class="weka.classifiers.pyscript.PyScriptClassifier" name="7">
            <object class="boolean" name="debug" primitive="yes">false</object>
            <object array="yes" class="java.lang.String" name="options">
               <object class="java.lang.String" name="0">-args</object>
               <object class="java.lang.String" name="1">regression=True;alpha=0.1;schedule=500;epochs=5000</object>
               <object class="java.lang.String" name="2">-batch</object>
               <object class="java.lang.String" name="3">10000</object>
               <object class="java.lang.String" name="4">-cmd</object>
               <object class="java.lang.String" name="5">python</object>
               <object class="java.lang.String" name="6">-script</object>
               <object class="java.lang.String" name="7">/home/cjb60/github/weka-pyscript-examples/test-kappa/train.py</object>
               <object class="java.lang.String" name="8">-binarize</object>